apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: introspec-xyz-tls
spec:
  secretName: introspec-xyz-tls
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: introspec.xyz
  dnsNames: 
    - introspec.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - introspec.xyz
          