apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: web
  template:
    metadata:
      labels:
        component: web
    spec: 
      containers: 
        - name: client
          image: kehindeadewusi/mclient
          resources:
            requests:
              memory: 200M
              cpu: 100m
            limits:
              memory: 200M
              cpu: 100m
          ports:
            - containerPort: 3000
